# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_secrets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='SiteUser',
        ),
        migrations.AddField(
            model_name='secret',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='dojos_secrets.SiteUser'),
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='dojos_secrets.SiteUser'),
        ),
    ]
