# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_secrets', '0002_auto_20170419_0731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteUser',
            new_name='User',
        ),
    ]
