# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_n_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='User',
        ),
    ]
