# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3791a7ebe06bdf321a927efabe2d973d2a19ced7d180b09c0a42fe83e18d70f7a6a9d2f5144ce1f885055e5e5f636712f0f16d880d0492961b0f0e142a8c6543

test:
  secret_key_base: 17c62f7d921850feaa7369f6cf4fb32ca40dde6a8069b3c7a93e1fa8406e6297ce14ed4738cf40362d98ef90ee9fcabd77586d079c92b3965183b9843543d1e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
