# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
