# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_auto_20170419_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='team',
        ),
        migrations.AddField(
            model_name='lineup',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='basketball.Team'),
            preserve_default=False,
        ),
    ]
